name: Build, Deploy, and Verify Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-deploy-verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker build -f docker/Dockerfile.backend -t ayush272002/automarker-backend:latest .
          docker push ayush272002/automarker-backend:latest

      - name: Build and push engine image
        run: |
          docker build -f docker/Dockerfile.engine -t ayush272002/automarker-engine:latest .
          docker push ayush272002/automarker-engine:latest

      - name: Verify backend image by pulling
        run: |
          docker pull ayush272002/automarker-backend:latest
          docker images | grep ayush272002/automarker-backend

      - name: Verify engine image by pulling
        run: |
          docker pull ayush272002/automarker-engine:latest
          docker images | grep ayush272002/automarker-engine
